version: "3.8"

include:
  - app1/common.yml
  - app2/common.yml

services:
  nginx:
    container_name: nginx
    #image: nginx:1.25.3-alpine
    build: nginx
    restart: always
    volumes:
      - ./app1/app/script/static/:/var/www
      - static:/var/www/css
    ports:
      - "443:443"
    networks:
      - nginx
    depends_on:
      - django
      - django2

  #not working for now
  caddy:
    image: caddy:2.7.6-alpine
    container_name: caddy
    profiles:
      - donotstart
    restart: always
    ports:
      - "448:448"
    networks:
      - nginx

networks:
  nginx:
    driver: bridge

volumes:
  static:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
