version: "3.8"

include:
  - site/common.yml

#services:
  #nginx:
  #  container_name: nginx
  #  build: nginx
  #  restart: always
  ##  volumes:
  #    - ./site/app/site/static/:/var/www #development purpose
  #  ports:
  #    - "443:443"
  #  networks:
  #    - nginx
  #  depends_on:
  #    - django

networks:
  nginx:
    driver: bridge

volumes:
  static:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
