version: "3.8"

include:
  - site/common.yml
  - rest/common.yml
  - restv2/common.yml
  - logs/common.yml
  - elk/common.yml

services:
  nginx:
    container_name: nginx
    build: nginx
    restart: always
    volumes:
      - ./site/app/script/static/:/var/www/ #development purpose
      - adm:/lib/adminer
        #- static:/var/www/css
    ports:
      - "443:443"
    networks:
      - nginx
    depends_on:
      django:
        condition: service_started
      django2:
        condition: service_started
      django3:
        condition: service_started
      kibana:
        condition: service_healthy

  adminer:
    container_name: adminer
    depends_on:
      postgres:
        condition: service_started
    build: ./adminer
    restart: always
    working_dir: /
    expose:
      - "8080"
    volumes:
      - adm:/lib/adminer
    networks:
      - db-network
      - nginx

networks:
  nginx:
    driver: bridge

  db-network:
    driver: bridge

volumes:
  static:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'

  adm: 
    driver: local
