version: "3.8"

include:
  - rest/common.yml

services:
  nginx:
    container_name: nginx
    build: nginx
    restart: always
    volumes:
      - ./site/app/site/static/:/var/www #development purpose
    ports:
      - "443:443"
    networks:
      - nginx
    depends_on:
      - django
  vault:
    container_name: vault
    build: vault
    networks:
      - app2
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ENABLE_FILE_PERMISSIONS_CHECK: True
      VAULT_ADDR: http://127.0.0.1:8200
    volumes:
      - vault:/opt

networks:
  nginx:
    driver: bridge

volumes:
  vault:
  static:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
