version: "3.8"

include:
  - users/common.yml

services:
  nginx:
    container_name: nginx
    build: nginx
    volumes:
      - ./users/users/script/static/:/var/www/ #development purpose
    restart: always
    ports:
      - "443:443"
    networks:
      - nginx
    depends_on:
      - django_users

networks:
  nginx:
    driver: bridge

volumes:
  static:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
