version: "3.8"

include:
<<<<<<< HEAD
  - rest/common.yml
=======
  - users/common.yml
>>>>>>> spa

services:
  nginx:
    container_name: nginx
    build: nginx
    volumes:
      - ./users/users/script/static/:/var/www/django/ #development purpose
      - ./nginx/site/:/var/www/html/ #development purpose
    restart: always
    ports:
      - "443:443"
      - "3000:3000"
    networks:
      - nginx
    depends_on:
<<<<<<< HEAD
      - django
  vault:
    container_name: vault
    build: vault
    networks:
      - app2
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ENABLE_FILE_PERMISSIONS_CHECK: True
      VAULT_ADDR: http://127.0.0.1:8200
    volumes:
      - vault:/opt
=======
      - django_users
>>>>>>> spa

networks:
  nginx:
    driver: bridge

volumes:
  vault:
  static:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
