version: "3.8"

include:
  - site/common.yml
  - rest/common.yml

services:
  nginx:
    container_name: nginx
    #image: nginx:1.25.3-alpine
    build: nginx
    restart: always
    volumes:
      - ./site/app/script/static/:/var/www/ #development purpose
        #- static:/var/www/css
    ports:
      - "443:443"
    networks:
      - nginx
    depends_on:
      - django
      - django2

networks:
  nginx:
    driver: bridge

volumes:
  static:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
