# Generated by Django 5.0.3 on 2024-03-23 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='UserGame',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
