# Generated by Django 5.0.3 on 2024-03-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_name',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_name',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
