<<<<<<< HEAD
# Generated by Django 5.0.3 on 2024-03-24 09:26
=======
# Generated by Django 5.0.3 on 2024-03-24 11:40
>>>>>>> 25aa94ff1fc03957e4b151522ba50082762f5784

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_gamer_nb_game_alter_gamer_victory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='nb_game',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='victory',
            field=models.IntegerField(default=0),
        ),
    ]
