# Generated by Django 5.0.3 on 2024-03-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_game_gamer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='conceded_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='marked_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponent',
            field=models.CharField(default='', max_length=50),
        ),
    ]
