# Generated by Django 5.0.3 on 2024-03-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_gamer_nb_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamer',
            name='nb_tournament',
            field=models.IntegerField(default=10),
        ),
    ]
