# Generated by Django 5.0.3 on 2024-03-25 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_game_conceded_point_alter_game_marked_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gamer'),
        ),
    ]
