# Generated by Django 5.0.1 on 2024-02-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_game_player1_game_player2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
