# Generated by Django 5.0.1 on 2024-01-17 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_testing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testing',
        ),
    ]
