# Generated by Django 5.0.2 on 2024-02-16 15:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tournamentgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentgame',
            name='users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None),
        ),
    ]
