# Generated by Django 5.0.1 on 2024-01-18 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_listing_band'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='band',
        ),
        migrations.DeleteModel(
            name='Band',
        ),
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
