# Generated by Django 5.0.1 on 2024-01-24 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pong',
        ),
    ]
