# Generated by Django 5.0.1 on 2024-01-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0010_delete_pong'),
    ]

    operations = [
        migrations.CreateModel(
            name='pong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
