# Generated by Django 5.0.1 on 2024-01-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pong',
        ),
    ]
