# Generated by Django 5.0.1 on 2024-01-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0012_delete_pong'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leftBox', models.IntegerField()),
                ('rightBox', models.IntegerField()),
            ],
        ),
    ]
