# Generated by Django 5.0.1 on 2024-01-31 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pong',
        ),
    ]
