#!/bin/bash -e

# Map environment variables to entries in logstash.yml.
# Note that this will mutate logstash.yml in place if any such settings are found.
# This may be undesirable, especially if logstash.yml is bind-mounted from the
# host system.

env2yaml /usr/share/logstash/config/logstash.yml

if [[ -n "$LOG_STYLE" ]]; then
  case "$LOG_STYLE" in
    console)
      # This is the default. Nothing to do.
      ;;
    file)
      # Overwrite the default config with the stack config. Do this as a
      # copy, not a move, in case the container is restarted.
      cp -f /usr/share/logstash/config/log4j2.file.properties /usr/share/logstash/config/log4j2.properties
      ;;
    *)
      echo "ERROR: LOG_STYLE set to [$LOG_STYLE]. Expected [console] or [file]" >&2
      exit 1 ;;
  esac
fi

export LS_JAVA_OPTS="-Dls.cgroup.cpuacct.path.override=/ -Dls.cgroup.cpu.path.override=/ $LS_JAVA_OPTS"

export VAULT_TOKEN=$(cat /opt/logstash_token)
export ELASTIC_USER=elastic
jsoncreds=$(curl --request GET --header "X-Vault-Token: $VAULT_TOKEN" http://vault:8200/v1/kv/elasticsearch)
export ELASTIC_PASSWORD=$(echo $jsoncreds | sed -n 's/.*"elastic":"\([^"]*\).*/\1/p')

if [[ -z $1 ]] || [[ ${1:0:1} == '-' ]] ; then
  exec logstash
else
  exec "$@"
fi

# recup la valeur echo "$json_data" | sed -n 's/.*"django_key":"\([^"]*\).*/\1/p'