version: "3.8"
services:
  postgres_pong:
    container_name: postgres_pong
    image: postgres:16.1-alpine3.19
    networks:
      - pong_network
      - vault_network_pong
      #- postgres_exporter-network
      #- logstash_network
    env_file:
      - ../.env
    environment:
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - PGPORT=5433
      - PGUSER=${PG_USER}
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5433"
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    
    
  django_pong:
    container_name: django_pong
    build: ./app
    networks:
      - pong_network 
      - nginx
      - vault_network_pong
    expose:
      - "8003" 
    restart: always
    volumes:
      - vault_django_pong:/opt
      - ./app/site/:/script/mysite #development purpose
    depends_on:
      postgres_pong:
        condition: service_healthy
    healthcheck:
      test: wget -qO- http://localhost:8003/health/
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  pong_network:
    driver: bridge
